title: <p align="center"> Tandeep Sandhu </p>
logo: /assets/img/logo_ts.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/tandeeps/">LinkedIn</a> |
  <a href="https://github.com/tandeeps">GitHub</a>
  
  <br> 

show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
